- lib/did_you_mean/levenshtein.rb
- test/similar_class_finder_test.rb
Prioritize suggestions where the only changes are upper-casing or
lower-casing characters in the string, by short-circuiting the
Levenshtein distance algorithm to return 1 if the strings are just
different-cased versions of each other.
There is almost definitely a better-optimized way of implementing this.
Fixes #38
> Prioritize suggestions with only case changes

- lib/did_you_mean/jaro_winkler.rb
- test/edit_distance/jaro_winkler_test.rb
FYI
```
did_you_mean $ env TEST=test/edit_distance/jaro_winkler_test.rb rake test
/Users/tonytonyjan/.rbenv/versions/2.2.3/bin/ruby -w -I"lib:test"  "/Users/tonytonyjan/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/edit_distance/jaro_winkler_test.rb"
Run options: --seed 58520
.F
Finished in 0.001189s, 1681.4240 runs/s, 12610.6797 assertions/s.
1) Failure:
JaroWinklerTest#test_jaro_winkler_distance [/Users/tonytonyjan/Dropbox/codes/gems/did_you_mean/test/edit_distance/jaro_winkler_test.rb:16]:
Expected: 1.0
Actual: 0.0
2 runs, 15 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test"  "/Users/tonytonyjan/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/edit_distance/jaro_winkler_test.rb" ] …
```
> add test case

- lib/did_you_mean/spell_checkers/name_error_checkers.rb
- test/core_ext/name_error_extension_test.rb
Actually, We cannot suggest from did_you_mean when typo at `Struct#[]` and `Struct#[]=` key.
```ruby
Foo = Struct.new(:foo)
Foo.new[:fooo]
#=> NameError: no member 'fooo' in struct
```
I want to save this case.
```ruby
Foo = Struct.new(:foo)
Foo.new[:fooo]
#=> NameError: no member 'fooo' in struct
Did you mean?  foo
foo=
```
Now, `"no member ..."` message only make from here https://github.com/ksss/ruby/blob/cee9c58ef214cbbf10aedacd79c3b796eb5bba8e/struct.c#L868
> Support Struct#[] and Struct#[]= typo

- evaluation/incorrect_words.yaml
The original comment included the same filename twice.
> Fix Birkbeck Spelling Error Corpus filename

- .travis.yml
Hello,
I want to use the latest version Ruby 2.4.1 in the `.travis.yml`.
Thanks.
> Update Ruby to lastet version 2.4.1 in .travis.yml

- lib/did_you_mean/spell_checkers/name_error_checkers.rb
`included` is called after the module has been included, and not called when `Object#extend`.
> prohibit including `NameErrorCheckers`

- lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
- test/spell_checker_test.rb
- test/spell_checking/variable_name_check_test.rb
Hi, @yuki24.
I'm thinking of adding predefined objects (`false`, `true`, and `nil`) in the variable name checker dictionary. Their 2.4 deprecated toplevel constants are already included, but the objects themselves are not.
The constants:
```ruby
a = NOL
b = FALS
c = TREU
```
but, the objects:
```ruby
a = nol
b = fals
c = treu
```
I need to be reminded of these objects too.
I don't know how to get the predefined objects in the nice way so I just write them in an array.
Since `nil` return `""` when called with `to_s`, I replaced it with `:nil`.
Should I wrote all of them in symbols ([:false, :true, :nil]) to make it consistent with the others?
If this PR is merged:
```ruby
a = nol
b = fals
c = treu
```
> Add ruby predefined objects to variable name checker

- .travis.yml
This PR adds ruby 2.6.0 into Travis.
> add ruby 2.6 to travis

- lib/did_you_mean.rb
Hey there - I was wondering if it might be possible to add a public API in order to register spell checkers. It's a pretty small change, but ergonomically it feels better than merging into a hash. I've added did_you_mean functionality to both thor and rubygems and it would feel better to call a blessed method.
Let me know what you think! Thanks for the great tool!
> Add a public API for registering an error

- lib/did_you_mean/spell_checker.rb
`Symbol#to_s` returns frozen string now.
> Simply turn into a string and downcase

- CHANGELOG.md
- README.md
- did_you_mean.gemspec
- documentation/changelog_generator.rb
- lib/did_you_mean/levenshtein.rb
- github.com/yuki24/did_you_mean -> github.com/ruby/did_you_mean
- travis-ci.org/yuki24/did_you_mean -> travis-ci.org/ruby/did_you_mean
> Update links because repository transferred

- .travis.yml
We don't have to run tasks like `test:accuracy` or `test:explore` in each build. The accuracy of the spell checker is independent of language runtime and the `benchmark:memory` is irrelevant in JRuby. We can just use the most recent Ruby to run these jobs.
> Extract accuracy/explore/memory menchmark tasks out of each build

- documentation/tree_spell_algorithm.md
- test/tree_spell/test_explore.rb
- test/tree_spell_checker_test.rb
When loaded into the Ruby repo, the place the test files are run from can change and it ends up messing up the file path. This changes it to be relative so that it maintains the correct linking.
> Fix up relative file paths for yml files

- lib/did_you_mean.rb
- lib/did_you_mean/experimental.rb
- lib/did_you_mean/experimental/initializer_name_correction.rb
- lib/did_you_mean/experimental/ivar_name_correction.rb
- lib/did_you_mean/spell_checker.rb
- lib/did_you_mean/spell_checkers/key_error_checker.rb
- lib/did_you_mean/spell_checkers/method_name_checker.rb
- lib/did_you_mean/spell_checkers/name_error_checkers.rb
- lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
- lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
- lib/did_you_mean/verbose.rb
- test/core_ext/test_name_error_extension.rb
- test/experimental/test_method_name_checker.rb
- test/helper.rb
- test/spell_checking/test_class_name_check.rb
- test/spell_checking/test_key_name_check.rb
- test/spell_checking/test_method_name_check.rb
- test/spell_checking/test_uncorrectable_name_check.rb
- test/spell_checking/test_variable_name_check.rb
- test/test_verbose_formatter.rb
- test/tree_spell/test_human_typo.rb
Two things are going wrong in the test suite for ruby core https://github.com/ruby/ruby/pull/2631. This attempts to fix both.
1. `assert_raises` throws a NoMethodError from within ruby core. Not sure why? It says to use `assert_raise` so that what I've gone and replaced everything with. Test suite still passes just fine so I imagine it's an alias in some versions of test/unit and not in others. Weird.
2. Due to the nature of how ruby core is running the tests, the bundled ruby did_you_mean is higher in the path than this gem's lib directory. So when you require did_you_mean, you actually end up testing the bundled version instead of the source code. Because of that, this commit changes the requires to be relative so that we're guaranteed to be requiring the correct code. There doesn't …
> Fixes for promotion to default gem

- lib/did_you_mean/experimental/ivar_name_correction.rb
- test/core_ext/test_name_error_extension.rb
- test/helper.rb
- test/test_verbose_formatter.rb
Okay I think these are probably the last two fixes needed for ruby core. Here they are:
1. When requiring the verbose formatter, it was using an absolute require instead of a require_relative, which gets messed up within the ruby core infra. This changes the requirement to be relative and to use the root determined by the test helper.
2. When experimental is turned on, the NoMethodError class was holding onto the @frame_binding instance variable, which made it unable to be dumped by Marshal. It doesn't appear that we actually need that instance variable once we've pulled out the instance variables names, so we can get rid of it.
> More fixes

- lib/did_you_mean/spell_checkers/method_name_checker.rb
- test/spell_checking/test_method_name_check.rb
For example, a reserved word `yield` is suggested agains `1.yeild`, but reserved words cannot be after a dot.
> Exclude reserved words from suggestion to non-private call

- CHANGELOG.md
- README.md
- benchmark/require_path_checker.rb
- lib/did_you_mean.rb
- lib/did_you_mean/spell_checkers/require_path_checker.rb
- test/spell_checking/test_require_path_check.rb
In response to https://bugs.ruby-lang.org/issues/16824, I'm adding a "did you mean?" to the `LoadError`. Here is an example of how it looks like:
```ruby
require 'net-http'
```
Finding suggestions on a large app could negatively impact the performance of the `LoadError#message`. On a 8-year old Rails app, there are 12676 requirable files:
```ruby
DidYouMean::RequirePathChecker.requireables.size
```
And there is a benchmark:
```
Warming up --------------------------------------
original (with a /)    25.000  i/100ms
original (without /)     8.000  i/100ms
Calculating -------------------------------------
original (with a /)    262.268  (± 4.2%) i/s -      2.625k in  10.028352s
original (without /)     74.966  (±17.3%) i/s -    712.000  in  10.015199s
Comparison:
original (with a /): …
```
> Suggest require paths on LoadError

- lib/did_you_mean/core_ext/name_error.rb
Previously, did_you_mean used `msg.end_with?(suggestion)` to check if
its suggestion is already added.
I'm now creating a gem that also modifies Exception's message. This
breaks did_you_mean's duplication check.
This change makes the check use String#include? instead of end_with?.
> Use String#include? instead of end_with? to avoid message duplication

- lib/did_you_mean/core_ext/name_error.rb
Previously, DidYouMean::Correctable#original_message did
`method(:to_s).super_method.call` to call the original to_s method by
skipping Correctable#to_s.
I'm now creating a gem that prepends another to_s method to NameError,
which confuses the hack. An immediate solution is to replace it with
`method(:to_s).super_method.super_method.call` to skip the two methods.
But it is too ad-hoc.
This changeset uses more extensible approach and allow a prepended
module to declare that they should be skipped by defining a constant
named `SKIP_TO_S_FOR_SUPER_LOOKUP`.
> Let Correctable#original_message skip prepended method definitions

- test/spell_checking/test_uncorrectable_name_check.rb
... instead of exact matching. I'm now creating a built-in gem that
modifies Exception's error message, so the expectation value is changed.
IMO, it is good to check that did_you_mean suggestion is NOT added in
the uncorrectable case.
> Use assert_not_match "Did you mean?" for UncorrectableNameCheckTest

- test/spell_checking/test_uncorrectable_name_check.rb
```
test/did_you_mean/spell_checking/test_uncorrectable_name_check.rb:13: warning: ambiguity between regexp and two divisions: wrap regexp in parentheses or add a space after `/' operator
```
http://rubyci.s3.amazonaws.com/ubuntu/ruby-master/log/20210630T033005Z.log.html.gz#test-all
> Prevent "warning: ambiguity between regexp and two divisions"

- README.md
This replaces the not-used Travis CI one.
> README: Use GitHub Actions build status badge

- CHANGELOG.md
This pull request fixes typo in CHANGELOG.
> Fix typo in CHANGELOG `DidYouMean::SPELL_CHECKERS`

- lib/did_you_mean/formatters/verbose_formatter.rb
```
did_you_mean/formatters/verbose_formatter.rb:5: warning: `frozen_string_literal' is ignored after any tokens
```
> Fix `frozen_string_literal is ignored after any tokens` warning.

- lib/did_you_mean/core_ext/name_error.rb
- test/core_ext/test_name_error_extension.rb
- test/helper.rb
- test/spell_checking/test_key_name_check.rb
- test/spell_checking/test_method_name_check.rb
- test/spell_checking/test_pattern_key_name_check.rb
- test/spell_checking/test_require_path_check.rb
- test/spell_checking/test_variable_name_check.rb
- test/test_ractor_compatibility.rb
This changeset lets DidYouMean::Correctable to use #detailed_message,
which is Ruby 3.2's more dedicated way to show additional error
information like did_you_mean and error_highlight.
There are some problems with the approach of overriding #message.
One is that the approach breaks a test that checks a return value
of #message. I actually faced this kind of issues in real-world
applications when I was implementing error_highlight with the same
approach as did_you_mean.
See https://github.com/minitest/minitest/pull/880 for example.
For this reason, error_highlight enhances only NameError.
The support of other error types such as TypeError and ArgumentError is
currently disabled because it breaks more tests:
https://github.com/ruby/error_highlight/blob/f88b6fab2ff34559a0f08d019d574dbb52426a2 …
> Define Exception#detailed_message instead of clobbering #message

- lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
- test/spell_checking/test_variable_name_check.rb
Fixed duplicates in corrections when passing method and variables with same name. Fixed #168
> Fixed correction duplicates in VaribaleNameChecker

- lib/did_you_mean/spell_checkers/method_name_checker.rb
- test/spell_checking/test_method_name_check.rb
A recent [discussion on Hacker News](https://news.ycombinator.com/item?id=33792874) reminded me of a particular type of suggestion that seems always irrelevant and potentially confusing. That would be suggesting `#foo` when someone calls `obj.foo = 1` or `#foo=` when someone calls `obj.foo`. I have actually seen inexperienced Rubyists read the message, scratch their heads, and try `obj.foo(1)` before moving on to their next idea.
Example:
```
3.1.2 :005 > book.title = "Programming Ruby"
(irb):5:in `<main>': undefined method `title=' for #<Book:0x00007f6b8842d650> (NoMethodError)
Did you mean?  title      
```
This is a fairly brute force implementation -- if the missing method name ends with =, only suggest methods that do, and vice versa. A more nuanced approach would be just to exclude …
> Do not suggest #name= for #name and vice versa

- test/core_ext/test_name_error_extension.rb
This change accepts the following change of the message of NameError in a test.
https://bugs.ruby-lang.org/issues/18285#note-37
```
old: undefined method `sizee' for #<File:...>
new: undefined method `sizee' for an instance of File
```
> Support the new message format of NameError in Ruby 3.3

- lib/did_you_mean/jaro_winkler.rb
The variable ``length2`` is an Integer, call to floor returns self.
The variables ``i`` and ``prefix_bonus`` are equally incremented, no need to keep the ``i`` variable.
> Remove Integer floor and prefix index from Jaro distance

- lib/did_you_mean.rb
It's for Ruby 3.4.
@yuki24 Can we release 1.7.0 with this change?
> Removed deprecated constants for Ruby 3.4

- test/spell_checking/test_require_path_check.rb
from https://bugs.ruby-lang.org/issues/20309
`ostruct` is will be bundled gems at Ruby 3.5. It means we can't load `ostruct` in ruby/ruby repository. I switched that to `open3` for similar usecase.
> Switch to use ostruct to open3 with suggestion test
